### ISSUE TITLE
can not build many error

### ISSUE THREAD

**Issue by zzxap** [rprx/XTLS#11]
..\github.com\xtls\go\key_schedule.go:46:12: undefined: hkdf.Expand
..\github.com\xtls\go\key_schedule.go:66:9: undefined: hkdf.Extract
..\github.com\xtls\go\key_schedule.go:114:30: undefined: curve25519.ScalarSize
..\github.com\xtls\go\key_schedule.go:118:21: undefined: curve25519.X25519
..\github.com\xtls\go\key_schedule.go:118:51: undefined: curve25519.Basepoint
..\github.com\xtls\go\key_schedule.go:194:20: undefined: curve25519.X25519

**Comment by RPRX** [comment]
Go 1.15+
