### ISSUE TITLE
vless的xtls和正常的https请求抓包有区别

### ISSUE THREAD

**Issue by usgate** [rprx/XTLS#3]
客户端和服务端已更新4.29.0，使用的推荐配置，开启xtls
正常网站的tls抓包
![image](https://user-images.githubusercontent.com/44760041/94417169-4fd38200-01b2-11eb-9011-0486b413ceeb.png)
 

xtls的抓包
![image](https://user-images.githubusercontent.com/44760041/94417299-7c879980-01b2-11eb-84e2-31de1c9b3e35.png)

都是从第一个包开始抓的

**Comment by RPRX** [comment]
1.第二张图中端口为 8080，或许 Wireshark 没有按 TLS 的方式去识别？因为不应该是这样。

2.v2ray 的 buffer size 为 2k(2048)，后续数据只要经过了就会被 2k 分割，所以它的本地抓包结果与 https 不完全相同。由于数据经公网多个设备间传输时也可能会被再次分割，本地的不同暂时不是严重问题（当然，也不好解决，但这属于调用方的问题）。

**Comment by usgate** [comment]
![image](https://user-images.githubusercontent.com/44760041/94435994-74d5ee00-01ce-11eb-9096-24cfb1cd0218.png)
这是vless 在8081端口的包，不存在wireshark识别问题。
xtls没有客户端和服务端tls协商加密算法的过程。
正常的tls通讯是可以识别tls版本的，但在xtls中并没有识别出来。

**Comment by RPRX** [comment]
XTLS 并没有魔改到那个地步。。。仍然认为是 Wireshark 识别问题，比如 8080 的只按 HTTP 来识别。

图二的第四个包，length 和图三的第四个包一样，都是 349。（此外图二含明显的干扰因素：63367、63368）

**Comment by usgate** [comment]
经确认，确实是wireshark识别问题
