### ISSUE TITLE
gollvm support for cpu/cpu_x86.s

### ISSUE THREAD

**Issue by advancedwebdeveloper** [rprx/XTLS#4]
I was trying to build [v2ray-core](https://github.com/v2fly/v2ray-core/issues/249) and caught some bugs:

> ~/go_projects/v2ray-core$ go test ./...
> # github.com/xtls/go/cpu
> vendor/github.com/xtls/go/cpu/cpu_x86.s: Assembler messages:
> vendor/github.com/xtls/go/cpu/cpu_x86.s:10: Error: no such instruction: `text ·cpuid(SB),NOSPLIT,$0-24'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:11: Error: junk `(FP)' after expression
> vendor/github.com/xtls/go/cpu/cpu_x86.s:11: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:12: Error: junk `(FP)' after expression
> vendor/github.com/xtls/go/cpu/cpu_x86.s:12: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:14: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:15: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:16: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:17: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:21: Error: no such instruction: `text ·xgetbv(SB),NOSPLIT,$0-8'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:24: Error: too many memory references for `mov'
> vendor/github.com/xtls/go/cpu/cpu_x86.s:25: Error: too many memory references for `mov'
> # v2ray.com/core/external/github.com/cloudflare/sidh/internal/utils
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s: Assembler messages:
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:5: Error: no such instruction: `text ·cpuid(SB),NOSPLIT,$0-4'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:6: Error: junk `(FP)' after expression
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:6: Error: too many memory references for `mov'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:7: Error: junk `(FP)' after expression
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:7: Error: too many memory references for `mov'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:9: Error: too many memory references for `mov'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:10: Error: too many memory references for `mov'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:11: Error: too many memory references for `mov'
> external/github.com/cloudflare/sidh/internal/utils/cpuid_amd64.s:12: Error: too many memory references for `mov'

[gollvm](https://go.googlesource.com/gollvm/) is used.
My [release](https://drive.google.com/file/d/15KD-isorTza_pLjg6l43Bxb1f0QNx4f5/view?usp=sharing) build.

CC @thanm @cherrymui

**Comment by RPRX** [comment]
https://github.com/v2fly/v2ray-core/issues/249

**Comment by RPRX** [comment]
Related https://github.com/v2fly/v2ray-core/issues/298
