### ISSUE TITLE
Proxy Protocol 支援問題

### ISSUE THREAD

**Issue by AkinoKaede** [rprx/XTLS#7]
目前，我使用了 Nginx 綁紮了 443 通訊埠，通過  ngx_stream_ssl_preread_module 檢查 SNI  並轉發到 VLESS 的通訊埠，我希望使 V2Ray 取得真實的用戶 IP，我嘗試在 xtlsSettings 中加入了  
```json
"acceptProxyProtocol": true
```
並在 Nginx 中設定  
```
proxy_protocol  on;
```
但這樣並不能正常工作。  
請問目前能夠支援或有計劃支援 Proxy Protocol 嗎

**Comment by RPRX** [comment]
首先，VLESS 和 v2ray 是 XX 界最早支持 PROXY protocol 的（先是 VLESS 回落，后是 v2ray 各个底层传输方式）。

配置方式有误，`"acceptProxyProtocol": true` 应写在 `tcpSettings` 内。https://www.v2fly.org/config/transport/tcp.html

**Comment by AkinoKaede** [comment]
感謝
